services:
    sourcebox.have_ibeen_pwned_cli.service.console_table_report_service:
        class: Sourcebox\HaveIBeenPwnedCLI\Service\ConsoleTableReportService

    sourcebox.have_ibeen_pwned_cli.console.command.csv_checker_command:
        class: Sourcebox\HaveIBeenPwnedCLI\Console\Command\CsvCheckerCommand
        arguments:
            - "@sourcebox.have_ibeen_pwned_cli.service.console_table_report_service"
        tags:
            - { name: console.command }