services:
    have_i_been_pwnded:
        class: xsist10\HaveIBeenPwned\HaveIBeenPwned

    console_output:
        class: Symfony\Component\Console\Output\ConsoleOutput

    sourcebox.finder_service.provider:
        class: Sourcebox\HaveIBeenPwnedCLI\Service\ServiceProvider

    sourcebox.report_service.provider:
        class: Sourcebox\HaveIBeenPwnedCLI\Service\ServiceProvider

    sourcebox.have_ibeen_pwned_cli.service.have_ibeen_pwned_breach_data_finder_service:
        class: Sourcebox\HaveIBeenPwnedCLI\Service\Finder\HaveIBeenPwnedFinderService
        arguments:
            - "@have_i_been_pwnded"
        tags:
            - { name: finder_service.provider, alias: haveibeenpwned }

    sourcebox.have_ibeen_pwned_cli.service.console_table_report_service:
        class: Sourcebox\HaveIBeenPwnedCLI\Service\Report\ConsoleTableReportService
        arguments:
            - "@console_output"
        tags:
            - { name: report_service.provider, alias: console }

    sourcebox.have_ibeen_pwned_cli.console.command.csv_checker_command:
        class: Sourcebox\HaveIBeenPwnedCLI\Console\Command\CsvCheckerCommand
        arguments:
            - "@sourcebox.finder_service.provider"
            - "@sourcebox.report_service.provider"
        tags:
            - { name: console.command }
